eureka:
  instance:
    nonSecurePort: 80
    hostname: ${vcap.application.uris[0]}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/