spring:
  application:
    name: cronos-checkout-api
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka.credentials.url}
  instance:
    preferIpAddress: true
    nonSecurePort: 80
    hostname: ${vcap.application.uris[0]}